keys:
  - &admin age1vl5e32vpsdfevc5k9zgz3p524dlt85pkw6u3wuufdrm54ewp0u6q24g8ve
  - hosts:
      - &host-recreate age12yf69pp0f9pj47fzlhfwp0zcg34v6kdhew2n3f5sf2czpjnen9uqs8q5lf
      - &host-worker age108cl60wjsjetdc5sd52wjnyw2jhpzck4k4dc7v5mupnp60jq9elqufjf8r
  - users:
      - &user-yeldir age1lk02y47avhuawmsrg9ear7znpcnn6s035kg54nfzmzr8eevhqcgs0f63j4
creation_rules:
  - path_regex: ^secrets\.yaml$
    key_groups:
      - age:
          - *admin
  - path_regex: hosts/shared/secrets\.yaml$
    key_groups:
      - age:
          - *admin
          - *host-recreate
          - *host-worker
  - path_regex: hosts/linux/recreate/secrets\.yaml$
    key_groups:
      - age:
          - *admin
          - *host-recreate
  - path_regex: home/yeldir/secrets\.yaml$
    key_groups:
      - age:
          - *admin
          - *user-yeldir
