#!/usr/bin/env sh
set -eu

session="default"
attach() {
  if [ -n "${TMUX:-}" ]; then
    tmux switch-client -t "=${session}"
  else
    tmux attach-session -t "=${session}"
  fi
}

if ! tmux has-session -t $session 2>/dev/null; then
  cd ~

  tmux new-session -d -s "${session}" -x "$(tput cols)" -y "$(tput lines)"
fi

attach
