#!/usr/bin/env bash
set -eu

if [[ -x "$(pwd)/tmux.sh" ]]; then
	echo "Found a tmux.sh script. Using that instead of default ide setup."
	"$(pwd)/tmux.sh"
	exit 0
fi

sessionSuffix="$(basename "$(pwd)")"
sessionSuffix="${sessionSuffix//./}"
sessionSuffix="${sessionSuffix//:/}"

session="ide-${sessionSuffix}"
attach() {
  if [ -n "${TMUX:-}" ]; then
    tmux switch-client -t "=${session}"
  else
    tmux attach-session -t "=${session}"
  fi
}

if ! tmux has-session -t "=${session}" 2>/dev/null; then
  tmux new-session -d -s "${session}" -x "$(tput cols)" -y "$(tput lines)"

  tmux split-window -t "${session}:0.0" -h -l "40%"

  sleep 1

  if [ -f "$(pwd)/devenv.nix" ]; then
    tmux send-keys -t "${session}:0.0" " devenv shell zsh" "C-m"
    tmux send-keys -t "${session}:0.1" " devenv shell zsh" "C-m"
  elif [ -f "$(pwd)/devbox.json" ]; then
    tmux send-keys -t "${session}:0.0" " devbox shell" "C-m"
    tmux send-keys -t "${session}:0.1" " devbox shell" "C-m"
  fi

  if is-git-bug-initialized; then
    tmux split-window -t "${session}:0.1" -v -l "20%" -b -d

    tmux send-keys -t "${session}:0.1" " git bug pull" "C-m"
    tmux send-keys -t "${session}:0.1" " git bug termui" "C-m"
  fi

  tmux send-keys -t "${session}:0.0" " nvim" "C-m"

  tmux select-window -t "${session}:0"
  tmux select-pane -t "${session}:0.0"
fi

attach
