#!/usr/bin/env bash
set -eu

# TODO: if a devbox.json file exists and it includes a "dev" command,
# run that command instead of all this.

sessionSuffix="$(basename "$(pwd)")"
sessionSuffix="${sessionSuffix//./}"
sessionSuffix="${sessionSuffix//:/}"

session="ide-${sessionSuffix}"
attach() {
  if [ -n "${TMUX:-}" ]; then
    tmux switch-client -t "=${session}"
  else
    tmux attach-session -t "=${session}"
  fi
}

if ! tmux has-session -t "${session}" 2>/dev/null; then
  tmux new-session -d -s "${session}" -x "$(tput cols)" -y "$(tput lines)"

  tmux split-window -t "${session}:0.0" -v
  tmux resize-pane -t "${session}:0.0" -y "30%"

  sleep 1

  if [ -f "$(pwd)/devbox.json" ]; then
    tmux send-keys -t "${session}:0.0" " devbox shell" "C-m"
    tmux send-keys -t "${session}:0.1" " devbox shell" "C-m"
  fi

  tmux send-keys -t "${session}:0.0" " nvim" "C-m"

  tmux select-window -t "${session}:0"
fi

attach
