#!/usr/bin/env bash
set -eu

session="nix"
attach() {
  if [ -n "${TMUX:-}" ]; then
    tmux switch-client -t "=${session}"
  else
    tmux attach-session -t "=${session}"
  fi
}

if ! tmux has-session -t $session 2>/dev/null; then
  cd ~/querbeet/workspace/nix-config

  tmux new-session -d -s "${session}" -n "nix" -x "$(tput cols)" -y "$(tput lines)"

  tmux split-window -t "${session}:nix.0" -h -l "40%"
  tmux split-window -t "${session}:nix.1" -v -l "80%"

  sleep 1

  tmux send-keys -t "${session}:nix.0" " devenv shell zsh" "C-m"
  tmux send-keys -t "${session}:nix.1" " devenv shell zsh" "C-m"
  tmux send-keys -t "${session}:nix.2" " devenv shell zsh" "C-m"

  tmux send-keys -t "${session}:nix.0" " nvim" "C-m"
  tmux send-keys -t "${session}:nix.0" " gg"

  tmux send-keys -t "${session}:nix.1" " git bug pull" "C-m"
  tmux send-keys -t "${session}:nix.1" " git bug termui" "C-m"

  tmux select-window -t "${session}:nix"
  tmux select-pane -t "${session}:nix.0"
fi

attach
