#!/usr/bin/env bash

ag --files-with-matches --literal "# [ <-- needed because of Argbash" |
while read -r template; do
	if [[ "${template}" = "scripts/build" ]]; then
		continue
	fi

	echo "building ${template}..."
	argbash --in-place "${template}"
done
