name: Update Flake Inputs

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * MON

permissions:
  contents: write
  pull-requests: write

jobs:
  update-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
      - name: Run nix-build
        run: |
          nix run nixpkgs#nixos-rebuild -- build --flake .#recreate
